QA_W1:
    home_Links:  
        1 : "Arrival Board"
        2 : "File Arrival Board"
        3 : "Arrival Boards Index"
        4 : "Delivery Boards Index"
        5 : "Transfers (main sites)"
        6 : "Transfers(configurable)"
        7 : "Summary Archive+Shelf"
        8 : "Shelf Use by Outlet"
        9 : "Shelf Use for Archive"
        10 : "Editors in use"
        11 : "JOE Restores Report"
        12 : "JOE Performance (Monthly) Report"
        13 : "JOE Monitoring Page"
    board_index_link:
        1 : "Arrival Plasma"
        2 : "File Plasma"
        3 : "Now & Next"
        4 : "Bookings Today"
        5 : "Recent JEX"
        6 : "JEX Today"
        7 : "JEX Exports"
        8 : "Recent JFE"
        9 : "JFE Today"
        10 : "Transfers In Now & Recent"
        11 : "Transfers In 12hr History"
        12 : "Transfers Out 12hr History"
        13 : "Site-to-Site Today"
        14 : "Transfers In & Out"
    editors_in_use_links:
        1 : "Grouped totals"
        2 : "Editors in use"
        3 : "sQ CutX totals"
        4 : "sQ EditX totals"
    pages:
        arrival: "http://qaw1.boards.jupiter.bbc.co.uk/boards/arrival/plasmaView.html"
        arrival_heading: "CB Start End Story Title Outlet Source Dest Via Rec AP Auto"
        now_next: "CB Start End Story Title Outlet Source Dest Via Rec AP Auto Status"
QA_USA:
    home_Links:  
        1 : "Arrival Board"
        2 : "File Arrival Board"
        3 : "Arrival Boards Index"
        4 : "Delivery Boards Index"
        5 : "Transfers (main sites)"
        6 : "Transfers(configurable)"
        7 : "Summary Archive+Shelf"
        8 : "Shelf Use by Outlet"
        9 : "Shelf Use for Archive"
        10 : "Editors in use"
        11 : "JOE Restores Report"
        12 : "JOE Performance (Monthly) Report"
        13 : "JOE Monitoring Page"
    board_index_link:
        1 : "Arrival Plasma"
        2 : "File Plasma"
        3 : "Now & Next"
        4 : "Bookings Today"
        5 : "Recent JEX"
        6 : "JEX Today"
        7 : "JEX Exports"
        8 : "Recent JFE"
        9 : "JFE Today"
        10 : "Transfers In Now & Recent"
        11 : "Transfers In 12hr History"
        12 : "Transfers Out 12hr History"
        13 : "Site-to-Site Today"
        14 : "Transfers In & Out"
    editors_in_use_links:
        1 : "Grouped totals"
        2 : "Editors in use"
        3 : "sQ CutX totals"
        4 : "sQ EditX totals"
    pages:
        arrival: "http://zgbwcusaapp04.jupiter.bbc.co.uk/boards/arrival/plasmaView.html"
        arrival_heading: "CB Start End Story Title Outlet Source Dest Via Rec AP Auto"
        now_next: "CB Start End Story Title Outlet Source Dest Via Rec AP Auto Status"